import { useState } from 'react'
import { useQuery, useMutation } from '@tanstack/react-query'
import { apiFetch, apiPost } from '../hooks/useApi'
import {
  Blocks, Play, Save, X, ChevronRight, ChevronDown, RefreshCw,
  TrendingUp, BarChart2, Repeat, DollarSign, Zap,
  Eye, Package, Store, ExternalLink, CheckCircle, AlertCircle,
  FlaskConical,
} from 'lucide-react'
import clsx from 'clsx'
import { useNavigate } from 'react-router-dom'

// ── Strategy Templates ─────────────────────────────────────────────

interface StrategyTemplate {
  id: string
  name: string
  description: string
  market: 'crypto' | 'polymarket_binary' | 'both'
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced'
  icon: React.ReactNode
  color: string
  params: TemplateParam[]
  generateCode: (params: Record<string, number | string>) => string
}

interface TemplateParam {
  key: string
  label: string
  description: string
  type: 'number' | 'select'
  default: number | string
  min?: number
  max?: number
  step?: number
  options?: { value: string; label: string }[]
}

const TEMPLATES: StrategyTemplate[] = [
  {
    id: 'btc_momentum',
    name: 'BTC Momentum',
    description: 'Follows BTC momentum using 4 confirmation signals: 4-candle momentum, 1-candle confirmation, RSI, and volume. Requires all 4 of 4 signals to enter.',
    market: 'crypto',
    difficulty: 'Beginner',
    icon: <TrendingUp size={24} />,
    color: '#f59e0b',
    params: [
      { key: 'interval_minutes', label: 'Candles (minutes)', description: 'Size of each candle in minutes', type: 'select', default: '4', options: [{ value: '1', label: '1 min' }, { value: '3', label: '3 min' }, { value: '4', label: '4 min' }, { value: '5', label: '5 min' }, { value: '15', label: '15 min' }] },
      { key: 'mom_threshold', label: '4-candle momentum threshold (%)', description: 'Minimum price change over 4 candles for signal', type: 'number', default: 1.8, min: 0.5, max: 5, step: 0.1 },
      { key: 'rsi_oversold', label: 'RSI oversold', description: 'RSI below this value = bullish signal', type: 'number', default: 25, min: 10, max: 40 },
      { key: 'rsi_overbought', label: 'RSI overbought', description: 'RSI above this value = bearish signal', type: 'number', default: 75, min: 60, max: 90 },
      { key: 'atr_sl_mult', label: 'Stop Loss Multiplier (ATR)', description: 'Stop loss = ATR × this value', type: 'number', default: 2.0, min: 0.5, max: 5, step: 0.5 },
      { key: 'atr_tp_mult', label: 'Take Profit Multiplier (ATR)', description: 'Take profit = ATR × this value', type: 'number', default: 3.0, min: 1, max: 10, step: 0.5 },
      { key: 'max_hold', label: 'Maximum candles in position', description: 'Close position after N candles', type: 'number', default: 8, min: 2, max: 50 },
    ],
    generateCode: (p) => `// ============================================================
// STRATEGY: BTC Momentum - Generated by Strategy Builder
// Market: Crypto (Binance)
// ============================================================

fn on_candle(ctx) {
    let lookback_4      = 4;
    let lookback_14     = 14;
    let lookback_50     = 50;
    let mom_threshold   = ${p.mom_threshold};
    let mom1_threshold  = ${Number(p.mom_threshold) / 3.6 | 0};
    let rsi_oversold    = ${p.rsi_oversold}.0;
    let rsi_overbought  = ${p.rsi_overbought}.0;
    let atr_sl_mult     = ${p.atr_sl_mult};
    let atr_tp_mult     = ${p.atr_tp_mult};
    let max_loss_pct    = 3.5;
    let take_pft_pct    = 6.0;
    let min_vol_mult    = 1.5;
    let max_hold        = ${p.max_hold};
    let min_idx         = 100;

    let idx = ctx.index;
    if idx < min_idx { return; }

    let close  = ctx.close;
    let volume = ctx.volume;
    let atr    = ctx.atr(14);

    if ctx.position != 0.0 {
        let ep        = ctx.entry_price;
        let bars_held = idx - ctx.entry_index;
        let pnl_pct   = if ep > 0.0 { (close - ep) / ep * 100.0 } else { 0.0 };
        let eff_pnl   = if ctx.position < 0.0 { -pnl_pct } else { pnl_pct };
        if eff_pnl >= take_pft_pct || eff_pnl <= -max_loss_pct || bars_held >= max_hold {
            ctx.sell(1.0);
        }
        return;
    }

    let close_4ago = ctx.close_at(idx - lookback_4);
    let mom4 = if close_4ago > 0.0 { (close - close_4ago) / close_4ago * 100.0 } else { 0.0 };
    let close_1ago = ctx.close_at(idx - 1);
    let mom1 = if close_1ago > 0.0 { (close - close_1ago) / close_1ago * 100.0 } else { 0.0 };
    let ema14 = ctx.ema(lookback_14);
    let sma50 = ctx.sma(lookback_50);
    let rsi   = ctx.rsi(lookback_14);
    let avg_vol = ctx.get("avg_vol", volume);
    ctx.set("avg_vol", avg_vol * 0.85 + volume * 0.15);
    let vol_ok = volume > avg_vol * min_vol_mult;

    let bull = 0;
    if mom4 > mom_threshold    { bull += 1; }
    if mom1 > mom1_threshold   { bull += 1; }
    if rsi < rsi_oversold      { bull += 1; }
    if vol_ok                  { bull += 1; }

    let bear = 0;
    if mom4 < -mom_threshold   { bear += 1; }
    if mom1 < -mom1_threshold  { bear += 1; }
    if rsi > rsi_overbought    { bear += 1; }
    if vol_ok                  { bear += 1; }

    if bull == 4 && close > ema14 && ema14 > sma50 {
        ctx.buy(1.0);
        ctx.set_stop_loss(close - atr * atr_sl_mult);
        ctx.set_take_profit(close + atr * atr_tp_mult);
    } else if bear == 4 && close < ema14 && ema14 < sma50 {
        ctx.sell(1.0);
        ctx.set_stop_loss(close + atr * atr_sl_mult);
        ctx.set_take_profit(close - atr * atr_tp_mult);
    }
}
`,
  },
  {
    id: 'polymarket_binary',
    name: 'Polymarket BTC UP/DOWN',
    description: 'Strategy for Polymarket binary markets. Compatible with all BTC/ETH recurring series (btc_5m, btc_4m, btc_15m, btc_1h, eth_5m, eth_15m). 3-of-4 confirmations with momentum, RSI and volume. The engine resolves each window automatically — no manual stop/take.',
    market: 'polymarket_binary',
    difficulty: 'Intermediate',
    icon: <BarChart2 size={24} />,
    color: '#00ff88',
    params: [
      { key: 'series', label: 'Target series', description: 'Select the series from the registry — only affects the generated comment. Use the same value in Backtesting -> series.', type: 'select', default: 'btc_5m', options: [
        { value: 'btc_5m',  label: 'BTC — 5-min binary' },
        { value: 'btc_4m',  label: 'BTC — 4-min binary' },
        { value: 'btc_15m', label: 'BTC — 15-min binary' },
        { value: 'btc_1h',  label: 'BTC — 1-hour binary' },
        { value: 'eth_5m',  label: 'ETH — 5-min binary' },
        { value: 'eth_15m', label: 'ETH — 15-min binary' },
      ]},
      { key: 'mom_threshold', label: '4-candle momentum threshold (%)', description: 'Minimum change over 4 candles for entry signal', type: 'number', default: 1.2, min: 0.3, max: 3, step: 0.1 },
      { key: 'rsi_oversold',  label: 'RSI oversold',   description: 'RSI below this value = BUY signal (bet YES: price goes up)', type: 'number', default: 30, min: 15, max: 45 },
      { key: 'rsi_overbought', label: 'RSI overbought', description: 'RSI above this value = SELL signal (bet NO: price goes down)', type: 'number', default: 70, min: 55, max: 85 },
      { key: 'min_confirmations', label: 'Minimum confirmations (out of 4)', description: 'How many signals are required to enter', type: 'select', default: '3', options: [
        { value: '2', label: '2 (more trades, less precise)' },
        { value: '3', label: '3 (optimal balance)' },
        { value: '4', label: '4 (very selective)' },
      ]},
      { key: 'min_vol_mult', label: 'Minimum volume multiplier', description: 'Volume must be X times the EMA average to confirm', type: 'number', default: 1.2, min: 1.0, max: 3.0, step: 0.1 },
    ],
    generateCode: (p) => `// ============================================================
// STRATEGY: Polymarket BTC UP/DOWN - Generated by Strategy Builder
// Target series  : ${p.series}
// Market         : Polymarket Binary  (market_type: polymarket_binary)
// Engine         : slug-aligned windows, automatic resolution by the engine
//
// ctx.buy(size)  = bet YES (price will rise in the window)
// ctx.sell(size) = bet NO  (price will drop or stay flat)
// Window resolves at the end — do NOT use manual stop_loss/take_profit.
// ctx.token_price = estimated YES token price (0-1 range)
// ============================================================

fn on_candle(ctx) {
    let min_idx           = 80;
    let mom_threshold     = ${p.mom_threshold};
    let mom1_threshold    = ${(Number(p.mom_threshold) * 0.25).toFixed(1)};
    let rsi_oversold      = ${p.rsi_oversold}.0;
    let rsi_overbought    = ${p.rsi_overbought}.0;
    let min_confirmations = ${p.min_confirmations};
    let min_vol_mult      = ${p.min_vol_mult};

    let idx = ctx.index;
    if idx < min_idx { return; }

    // Engine already resolved the previous window before calling on_candle
    // Only enter if there is no open position
    if ctx.position != 0.0 { return; }

    let close  = ctx.close;
    let volume = ctx.volume;

    // Indicators
    let close_4ago = ctx.close_at(idx - 4);
    let mom4 = if close_4ago > 0.0 { (close - close_4ago) / close_4ago * 100.0 } else { 0.0 };
    let close_1ago = ctx.close_at(idx - 1);
    let mom1 = if close_1ago > 0.0 { (close - close_1ago) / close_1ago * 100.0 } else { 0.0 };
    let ema14 = ctx.ema(14);
    let rsi   = ctx.rsi(14);
    let avg_vol = ctx.get("avg_vol", volume);
    ctx.set("avg_vol", avg_vol * 0.9 + volume * 0.1);
    let vol_ok = volume > avg_vol * min_vol_mult;

    // Bullish signals (bet YES: BTC will rise)
    let bull = 0;
    if mom4 > mom_threshold   { bull += 1; }  // 4-candle bullish momentum
    if mom1 > mom1_threshold  { bull += 1; }  // last close higher
    if rsi < rsi_oversold     { bull += 1; }  // RSI oversold (rebound expected)
    if vol_ok                 { bull += 1; }  // volume confirmation

    // Bearish signals (bet NO: BTC will drop)
    let bear = 0;
    if mom4 < -mom_threshold  { bear += 1; }  // 4-candle bearish momentum
    if mom1 < -mom1_threshold { bear += 1; }  // last close lower
    if rsi > rsi_overbought   { bear += 1; }  // RSI overbought (drop expected)
    if vol_ok                 { bear += 1; }  // volume confirmation

    // Decision
    if bull >= min_confirmations && close > ema14 {
        ctx.buy(1.0);  // YES: BTC will rise in the window
    } else if bear >= min_confirmations && close < ema14 {
        ctx.sell(1.0); // NO: BTC will drop in the window
    }
}

// ============================================================
// HOW TO USE IN BACKTESTING:
// 1. Backtesting -> Market: Polymarket Binary
// 2. Series: ${p.series}  (select in the panel)
// 3. Range: 3 months for reliable statistics
// Slug formula: btc-updown-5m-{window_ts}
//   where window_ts = unix_ts - (unix_ts % 300)
// ============================================================
`,
  },
  {
    id: 'weather_binary',
    name: 'Polymarket Weather Binary',
    description: 'Template for recurring weather markets (threshold_above / threshold_below) using Open-Meteo data and threshold rules.',
    market: 'polymarket_binary',
    difficulty: 'Intermediate',
    icon: <BarChart2 size={24} />,
    color: '#38bdf8',
    params: [
      { key: 'series', label: 'Weather series', description: 'Select a weather series from the registry', type: 'select', default: 'munich_temp_daily', options: [
        { value: 'munich_temp_daily', label: 'Munich temp > 25°C' },
        { value: 'london_temp_daily', label: 'London temp > 22°C' },
        { value: 'nyc_temp_daily', label: 'NYC temp > 28°C' },
      ]},
      { key: 'threshold', label: 'Threshold', description: 'Threshold value to resolve the market', type: 'number', default: 25, min: -20, max: 60, step: 0.5 },
      { key: 'yes_score', label: 'Minimum YES score', description: 'Score threshold to bet YES', type: 'number', default: 3.5, min: 1.0, max: 8.0, step: 0.5 },
      { key: 'no_score', label: 'Maximum NO score', description: 'Score threshold to bet NO', type: 'number', default: -3.5, min: -8.0, max: -1.0, step: 0.5 },
    ],
    generateCode: (p) => `// ============================================================
// STRATEGY: Polymarket Weather Binary - Generated by Strategy Builder
// Target series  : ${p.series}
// Data source    : Open-Meteo (daily candles)
// Resolution     : threshold_above / threshold_below (per series config)
// Threshold      : ${p.threshold}
// ============================================================

fn on_candle(ctx) {
    let warmup = 14;
    if ctx.index < warmup { return; }

    let value     = ctx.close;
    let threshold = ${p.threshold}.0;

    let ema7  = ctx.ema(7);
    let ema14 = ctx.ema(14);
    let score = 0.0;

    if ema7 > threshold + 1.0       { score += 3.0; }
    else if ema7 > threshold         { score += 1.5; }
    else if ema7 < threshold - 1.0   { score -= 3.0; }
    else                             { score -= 1.5; }

    if ema7 > ema14 { score += 1.0; }
    else            { score -= 1.0; }

    let dist = value - threshold;
    if dist > 2.0        { score += 2.0; }
    else if dist > 0.0   { score += 0.5; }
    else if dist < -2.0  { score -= 2.0; }
    else                 { score -= 0.5; }

    if ctx.position != 0.0 { return; }

    if score >= ${p.yes_score} {
        ctx.buy(0.4);
    } else if score <= ${p.no_score} {
        ctx.sell(0.4);
    }
}
`,
  },
  {
    id: 'mean_reversion',
    name: 'Mean Reversion (RSI)',
    description: 'Counter-trend strategy: buys when price is deeply oversold and sells when overbought. Best for ranging markets. Uses RSI + distance from EMA.',
    market: 'crypto',
    difficulty: 'Beginner',
    icon: <Repeat size={24} />,
    color: '#8b5cf6',
    params: [
      { key: 'rsi_buy', label: 'RSI to buy (oversold)', description: 'Buy when RSI drops below this value', type: 'number', default: 25, min: 10, max: 40 },
      { key: 'rsi_sell', label: 'RSI to sell (overbought)', description: 'Sell when RSI rises above this value', type: 'number', default: 75, min: 60, max: 90 },
      { key: 'ema_period', label: 'EMA period', description: 'Exponential moving average as price reference', type: 'number', default: 20, min: 5, max: 100 },
      { key: 'take_pft_pct', label: 'Take profit (%)', description: 'Exit when profit reaches this percentage', type: 'number', default: 4.0, min: 0.5, max: 20, step: 0.5 },
      { key: 'max_loss_pct', label: 'Stop loss (%)', description: 'Exit if loss exceeds this percentage', type: 'number', default: 3.0, min: 0.5, max: 10, step: 0.5 },
      { key: 'max_hold', label: 'Maximum candles in position', description: 'Close position after N candles without resolution', type: 'number', default: 20, min: 5, max: 100 },
    ],
    generateCode: (p) => `// ============================================================
// STRATEGY: Mean Reversion RSI - Generated by Strategy Builder
// Market: Crypto
// ============================================================

fn on_candle(ctx) {
    let rsi_buy      = ${p.rsi_buy}.0;
    let rsi_sell     = ${p.rsi_sell}.0;
    let ema_period   = ${p.ema_period};
    let take_pft_pct = ${p.take_pft_pct};
    let max_loss_pct = ${p.max_loss_pct};
    let max_hold     = ${p.max_hold};
    let min_idx      = 50;

    let idx = ctx.index;
    if idx < min_idx { return; }

    let close = ctx.close;
    let rsi   = ctx.rsi(14);
    let ema   = ctx.ema(ema_period);

    if ctx.position != 0.0 {
        let ep        = ctx.entry_price;
        let bars_held = idx - ctx.entry_index;
        let pnl_pct   = if ep > 0.0 { (close - ep) / ep * 100.0 } else { 0.0 };
        let eff_pnl   = if ctx.position < 0.0 { -pnl_pct } else { pnl_pct };
        if eff_pnl >= take_pft_pct || eff_pnl <= -max_loss_pct || bars_held >= max_hold {
            ctx.sell(1.0);
        }
        return;
    }

    // Buy when oversold + price below EMA (reversal expected upward)
    if rsi < rsi_buy && close < ema {
        ctx.buy(1.0);
        ctx.log("MEAN REVERSION BUY: rsi=" + rsi + " close=" + close + " ema=" + ema);
    }

    // Short sell when overbought + price above EMA
    if rsi > rsi_sell && close > ema {
        ctx.sell(1.0);
        ctx.log("MEAN REVERSION SELL: rsi=" + rsi + " close=" + close + " ema=" + ema);
    }
}
`,
  },
  {
    id: 'dca_bot',
    name: 'DCA Bot (Dollar Cost Averaging)',
    description: 'Buys at regular intervals regardless of price. Long-term strategy that averages the entry cost. No shorts, only gradual accumulation.',
    market: 'crypto',
    difficulty: 'Beginner',
    icon: <DollarSign size={24} />,
    color: '#06b6d4',
    params: [
      { key: 'buy_interval', label: 'Buy every N candles', description: 'Interval between buys (in number of candles)', type: 'number', default: 24, min: 1, max: 200 },
      { key: 'rsi_dip_threshold', label: 'RSI for extra buy (dip)', description: 'If RSI drops below this value, buy extra', type: 'number', default: 35, min: 15, max: 50 },
      { key: 'take_pft_pct', label: 'Take profit (%)', description: 'Sell when profit reaches this percentage', type: 'number', default: 10.0, min: 2, max: 50, step: 0.5 },
    ],
    generateCode: (p) => `// ============================================================
// STRATEGY: DCA Bot - Generated by Strategy Builder
// Market: Crypto (long-term accumulation)
// ============================================================

fn on_candle(ctx) {
    let buy_interval      = ${p.buy_interval};
    let rsi_dip_threshold = ${p.rsi_dip_threshold}.0;
    let take_pft_pct      = ${p.take_pft_pct};
    let min_idx           = 50;

    let idx = ctx.index;
    if idx < min_idx { return; }

    let close = ctx.close;
    let rsi   = ctx.rsi(14);

    // Take profit if position is active and profit is sufficient
    if ctx.position > 0.0 {
        let ep      = ctx.entry_price;
        let pnl_pct = if ep > 0.0 { (close - ep) / ep * 100.0 } else { 0.0 };
        if pnl_pct >= take_pft_pct {
            ctx.sell(1.0);
            ctx.log("DCA PROFIT TAKE: pnl=" + pnl_pct + "%");
        }
        return;
    }

    // Buy at regular interval
    let regular_buy = (idx % buy_interval) == 0;

    // Also buy on strong drops (RSI dip)
    let dip_buy = rsi < rsi_dip_threshold;

    if regular_buy || dip_buy {
        ctx.buy(1.0);
        if dip_buy {
            ctx.log("DCA DIP BUY: rsi=" + rsi + " (dip detected)");
        } else {
            ctx.log("DCA REGULAR BUY: candle=" + idx);
        }
    }
}
`,
  },
  {
    id: 'pump_detection',
    name: 'Pump Detection (Volume)',
    description: 'Detects "pumps" (sudden spikes with high volume) and trades in the direction of the move. Best for high-volatility moments and news events.',
    market: 'both',
    difficulty: 'Advanced',
    icon: <Zap size={24} />,
    color: '#ef4444',
    params: [
      { key: 'vol_spike_mult', label: 'Volume multiplier (spike)', description: 'Volume must be X times the average to confirm a pump', type: 'number', default: 3.0, min: 1.5, max: 10, step: 0.5 },
      { key: 'mom_threshold', label: 'Momentum threshold (%)', description: 'Minimum price change to confirm pump', type: 'number', default: 2.5, min: 0.5, max: 10, step: 0.5 },
      { key: 'take_pft_pct', label: 'Take profit (%)', description: 'Exit quickly with this profit percentage', type: 'number', default: 3.0, min: 0.5, max: 15, step: 0.5 },
      { key: 'max_loss_pct', label: 'Stop loss (%)', description: 'Exit quickly if the pump fails', type: 'number', default: 1.5, min: 0.3, max: 5, step: 0.1 },
      { key: 'max_hold', label: 'Maximum candles (fast exit)', description: 'Pumps are brief: close within N candles', type: 'number', default: 5, min: 1, max: 20 },
    ],
    generateCode: (p) => `// ============================================================
// STRATEGY: Pump Detection - Generated by Strategy Builder
// Market: Crypto / Polymarket
// ============================================================

fn on_candle(ctx) {
    let vol_spike_mult = ${p.vol_spike_mult};
    let mom_threshold  = ${p.mom_threshold};
    let take_pft_pct   = ${p.take_pft_pct};
    let max_loss_pct   = ${p.max_loss_pct};
    let max_hold       = ${p.max_hold};
    let min_idx        = 30;

    let idx    = ctx.index;
    if idx < min_idx { return; }

    let close  = ctx.close;
    let volume = ctx.volume;

    if ctx.position != 0.0 {
        let ep        = ctx.entry_price;
        let bars_held = idx - ctx.entry_index;
        let pnl_pct   = if ep > 0.0 { (close - ep) / ep * 100.0 } else { 0.0 };
        let eff_pnl   = if ctx.position < 0.0 { -pnl_pct } else { pnl_pct };
        if eff_pnl >= take_pft_pct || eff_pnl <= -max_loss_pct || bars_held >= max_hold {
            ctx.sell(1.0);
            ctx.log("PUMP EXIT: pnl=" + eff_pnl + "% bars=" + bars_held);
        }
        return;
    }

    // Volume spike detection
    let avg_vol = ctx.get("avg_vol", volume);
    ctx.set("avg_vol", avg_vol * 0.9 + volume * 0.1);
    let vol_spike = volume > avg_vol * vol_spike_mult;

    // Momentum
    let prev_close = ctx.close_at(idx - 1);
    let mom1 = if prev_close > 0.0 { (close - prev_close) / prev_close * 100.0 } else { 0.0 };

    // Only enter on volume spike + strong momentum
    if vol_spike {
        if mom1 > mom_threshold {
            ctx.buy(1.0);
            ctx.log("PUMP UP: vol=" + (volume / avg_vol) + "x mom=" + mom1 + "%");
        } else if mom1 < -mom_threshold {
            ctx.sell(1.0);
            ctx.log("PUMP DOWN: vol=" + (volume / avg_vol) + "x mom=" + mom1 + "%");
        }
    }
}
`,
  },
]

// ── Agent Skills types (kept from Skills page) ────────────────────

interface AgentSkill {
  name: string
  description: string
  version: string
  author?: string
  tags: string[]
  location: string
}

interface SkillsResponse {
  skills: AgentSkill[]
}

interface BacktestScript {
  name: string
  path: string
  description?: string
}

// ── Template Card ─────────────────────────────────────────────────

function TemplateCard({
  template,
  onSelect,
}: {
  template: StrategyTemplate
  onSelect: () => void
}) {
  const marketLabel = {
    crypto: 'Crypto (Binance)',
    polymarket_binary: 'Polymarket Binary',
    both: 'Crypto + Polymarket',
  }[template.market]

  const diffColor = {
    Beginner: 'var(--color-accent)',
    Intermediate: '#f59e0b',
    Advanced: 'var(--color-danger)',
  }[template.difficulty]

  return (
    <div
      className="rounded-lg border p-5 cursor-pointer transition-all hover:scale-[1.02] group"
      style={{ backgroundColor: 'var(--color-surface)', borderColor: 'var(--color-border)' }}
      onClick={onSelect}
    >
      <div className="flex items-start gap-3 mb-3">
        <div
          className="p-2 rounded flex-shrink-0"
          style={{ backgroundColor: `${template.color}20`, color: template.color }}
        >
          {template.icon}
        </div>
        <div className="flex-1 min-w-0">
          <h3 className="text-sm font-bold mb-1" style={{ color: 'var(--color-text)' }}>
            {template.name}
          </h3>
          <div className="flex items-center gap-2 flex-wrap">
            <span
              className="text-[10px] px-2 py-0.5 rounded font-semibold uppercase tracking-wider"
              style={{ backgroundColor: 'var(--color-surface-2)', color: 'var(--color-text-muted)' }}
            >
              {marketLabel}
            </span>
            <span
              className="text-[10px] px-2 py-0.5 rounded font-semibold uppercase tracking-wider"
              style={{ color: diffColor, backgroundColor: `${diffColor}20` }}
            >
              {template.difficulty}
            </span>
          </div>
        </div>
      </div>
      <p className="text-xs leading-relaxed mb-4" style={{ color: 'var(--color-text-muted)' }}>
        {template.description}
      </p>
      <button
        className="w-full flex items-center justify-center gap-2 py-2 rounded text-sm font-semibold transition-colors"
        style={{ backgroundColor: `${template.color}20`, color: template.color }}
      >
        <Play size={13} />
        Create Strategy
        <ChevronRight size={13} className="group-hover:translate-x-0.5 transition-transform" />
      </button>
    </div>
  )
}

// ── Strategy Creation Wizard ──────────────────────────────────────

function StrategyWizard({
  template,
  scriptsBasePath,
  onClose,
  onCreated,
}: {
  template: StrategyTemplate
  scriptsBasePath: string
  onClose: () => void
  onCreated: (name: string) => void
}) {
  const [params, setParams] = useState<Record<string, number | string>>(() => {
    const init: Record<string, number | string> = {}
    template.params.forEach(p => { init[p.key] = p.default })
    return init
  })
  const [strategyName, setStrategyName] = useState(
    template.name.toLowerCase().replace(/[^a-z0-9]+/g, '_') + '_custom'
  )
  const [previewOpen, setPreviewOpen] = useState(false)
  const [saved, setSaved] = useState(false)

  const code = template.generateCode(params)
  const filename = strategyName.endsWith('.rhai') ? strategyName : `${strategyName}.rhai`

  const saveMutation = useMutation({
    mutationFn: () => {
      const path = `${scriptsBasePath}/${filename}`
      return apiPost('/api/backtest/scripts/content', { path, content: code })
    },
    onSuccess: () => {
      setSaved(true)
      setTimeout(() => onCreated(filename), 800)
    },
  })

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ backgroundColor: 'rgba(0,0,0,0.8)' }}
      onClick={onClose}
    >
      <div
        className="w-full max-w-2xl max-h-[90vh] rounded-lg border flex flex-col"
        style={{ backgroundColor: 'var(--color-surface)', borderColor: 'var(--color-border)' }}
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b" style={{ borderColor: 'var(--color-border)' }}>
          <div className="flex items-center gap-3">
            <div
              className="p-1.5 rounded"
              style={{ backgroundColor: `${template.color}20`, color: template.color }}
            >
              {template.icon}
            </div>
            <div>
              <h2 className="text-sm font-bold">Create: {template.name}</h2>
              <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>
                Adjust parameters and save the strategy
              </p>
            </div>
          </div>
          <button onClick={onClose}>
            <X size={16} style={{ color: 'var(--color-text-muted)' }} />
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-5 space-y-4">
          {/* Strategy name */}
          <div>
            <label className="block text-xs font-semibold mb-1.5" style={{ color: 'var(--color-text-muted)' }}>
              File name
            </label>
            <input
              value={strategyName}
              onChange={e => setStrategyName(e.target.value.replace(/[^a-z0-9_]/gi, '_').toLowerCase())}
              className="w-full rounded px-3 py-2 text-sm font-mono"
              style={{
                backgroundColor: 'var(--color-surface-2)',
                border: '1px solid var(--color-border)',
                color: 'var(--color-text)',
              }}
              placeholder="strategy_name"
            />
            <p className="text-xs mt-1" style={{ color: 'var(--color-text-muted)' }}>
              Will be saved as: <code>{filename}</code>
            </p>
          </div>

          {/* Parameters */}
          <div>
            <h3 className="text-xs font-semibold uppercase tracking-widest mb-3" style={{ color: 'var(--color-text-muted)' }}>
              Parameters
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {template.params.map(param => (
                <div key={param.key}>
                  <label className="block text-xs font-medium mb-1" style={{ color: 'var(--color-text)' }}>
                    {param.label}
                  </label>
                  {param.type === 'select' ? (
                    <select
                      value={params[param.key] as string}
                      onChange={e => setParams(prev => ({ ...prev, [param.key]: e.target.value }))}
                      className="w-full rounded px-2 py-1.5 text-sm"
                      style={{
                        backgroundColor: 'var(--color-surface-2)',
                        border: '1px solid var(--color-border)',
                        color: 'var(--color-text)',
                      }}
                    >
                      {param.options!.map(opt => (
                        <option key={opt.value} value={opt.value}>{opt.label}</option>
                      ))}
                    </select>
                  ) : (
                    <input
                      type="number"
                      min={param.min}
                      max={param.max}
                      step={param.step ?? 1}
                      value={params[param.key] as number}
                      onChange={e => setParams(prev => ({ ...prev, [param.key]: Number(e.target.value) }))}
                      className="w-full rounded px-2 py-1.5 text-sm font-mono"
                      style={{
                        backgroundColor: 'var(--color-surface-2)',
                        border: '1px solid var(--color-border)',
                        color: 'var(--color-text)',
                      }}
                    />
                  )}
                  <p className="text-[10px] mt-0.5" style={{ color: 'var(--color-text-muted)' }}>
                    {param.description}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Code preview toggle */}
          <div>
            <button
              onClick={() => setPreviewOpen(v => !v)}
              className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest"
              style={{ color: 'var(--color-text-muted)' }}
            >
              {previewOpen ? <ChevronDown size={12} /> : <ChevronRight size={12} />}
              <Eye size={12} />
              Code preview
            </button>
            {previewOpen && (
              <pre
                className="mt-2 p-3 rounded text-xs font-mono overflow-auto max-h-64"
                style={{ backgroundColor: 'var(--color-surface-2)', color: 'var(--color-text)' }}
              >
                {code}
              </pre>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between px-5 py-4 border-t" style={{ borderColor: 'var(--color-border)' }}>
          <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>
            {saved ? (
              <span className="flex items-center gap-1" style={{ color: 'var(--color-accent)' }}>
                <CheckCircle size={12} />
                Saved! Available in Backtesting.
              </span>
            ) : (
              'The strategy will be available in Backtesting and Live Strategies'
            )}
          </p>
          <div className="flex gap-2">
            <button onClick={onClose} className="px-3 py-1.5 rounded text-sm" style={{ color: 'var(--color-text-muted)' }}>
              Cancel
            </button>
            <button
              onClick={() => saveMutation.mutate()}
              disabled={saveMutation.isPending || saved || !strategyName}
              className="flex items-center gap-2 px-4 py-1.5 rounded text-sm font-semibold disabled:opacity-50"
              style={{ backgroundColor: 'var(--color-accent)', color: '#000' }}
            >
              {saveMutation.isPending ? (
                <><RefreshCw size={12} className="animate-spin" /> Saving...</>
              ) : saved ? (
                <><CheckCircle size={12} /> Saved</>
              ) : (
                <><Save size={12} /> Save Strategy</>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

// ── Main Page ─────────────────────────────────────────────────────

export default function StrategyBuilder() {
  const navigate = useNavigate()
  const [selectedTemplate, setSelectedTemplate] = useState<StrategyTemplate | null>(null)
  const [viewingSkill, setViewingSkill] = useState<AgentSkill | null>(null)
  const [showCreatedBanner, setShowCreatedBanner] = useState<string | null>(null)

  // Get scripts to determine base path
  const { data: scriptsData } = useQuery<{ scripts: BacktestScript[] }>({
    queryKey: ['backtest-scripts-builder'],
    queryFn: () => apiFetch('/api/backtest/scripts'),
    staleTime: 30_000,
  })

  // Derive base scripts path from first script path
  const scriptsBasePath = (() => {
    const scripts = scriptsData?.scripts ?? []
    if (scripts.length === 0) return ''
    const firstPath = scripts[0].path
    const parts = firstPath.split('/')
    parts.pop()
    return parts.join('/')
  })()

  // Agent skills
  const { data: skillsData, isLoading: skillsLoading } = useQuery<SkillsResponse>({
    queryKey: ['agent-skills'],
    queryFn: () => apiFetch<SkillsResponse>('/api/skills').catch(() => ({ skills: [] })),
    refetchInterval: 30_000,
  })
  const skills = skillsData?.skills ?? []

  function handleCreated(filename: string) {
    setSelectedTemplate(null)
    setShowCreatedBanner(filename)
    setTimeout(() => setShowCreatedBanner(null), 5000)
  }

  return (
    <div className="p-6 max-w-5xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-2">
          <Blocks size={20} style={{ color: 'var(--color-accent)' }} />
          <div>
            <h1 className="text-lg font-bold">Strategy Builder</h1>
            <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>
              Create trading strategies without coding experience
            </p>
          </div>
        </div>
        <button
          onClick={() => navigate('/backtesting')}
          className="flex items-center gap-2 px-3 py-1.5 rounded text-sm border hover:bg-white/5 transition-colors"
          style={{ borderColor: 'var(--color-border)', color: 'var(--color-text-muted)' }}
        >
          <FlaskConical size={13} />
          Go to Backtesting
        </button>
      </div>

      {/* Created banner */}
      {showCreatedBanner && (
        <div
          className="rounded-lg border px-4 py-3 mb-6 flex items-center gap-3"
          style={{ backgroundColor: 'rgba(0,255,136,0.06)', borderColor: 'rgba(0,255,136,0.3)' }}
        >
          <CheckCircle size={16} style={{ color: 'var(--color-accent)' }} />
          <span className="text-sm" style={{ color: 'var(--color-text)' }}>
            Strategy <strong>{showCreatedBanner}</strong> created successfully.
            Now available in{' '}
            <button onClick={() => navigate('/backtesting')} className="underline font-semibold" style={{ color: 'var(--color-accent)' }}>
              Backtesting
            </button>{' '}
            and{' '}
            <button onClick={() => navigate('/live')} className="underline font-semibold" style={{ color: 'var(--color-accent)' }}>
              Live Strategies
            </button>.
          </span>
          <button onClick={() => setShowCreatedBanner(null)} className="ml-auto">
            <X size={14} style={{ color: 'var(--color-text-muted)' }} />
          </button>
        </div>
      )}

      {/* Templates Section */}
      <div className="mb-8">
        <div className="flex items-center gap-2 mb-4">
          <div
            className="w-1 h-5 rounded"
            style={{ backgroundColor: 'var(--color-accent)' }}
          />
          <h2 className="text-sm font-bold uppercase tracking-widest" style={{ color: 'var(--color-text)' }}>
            Strategy Templates
          </h2>
          <span
            className="text-xs px-2 py-0.5 rounded"
            style={{ backgroundColor: 'var(--color-accent-dim)', color: 'var(--color-accent)' }}
          >
            {TEMPLATES.length} templates
          </span>
        </div>
        <p className="text-xs mb-4" style={{ color: 'var(--color-text-muted)' }}>
          Select a template, adjust parameters with simple controls, and generate your strategy ready for backtesting.
          No coding knowledge required.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {TEMPLATES.map(template => (
            <TemplateCard
              key={template.id}
              template={template}
              onSelect={() => setSelectedTemplate(template)}
            />
          ))}
        </div>
      </div>

      {/* How it works */}
      <div
        className="rounded-lg border p-5 mb-8"
        style={{ backgroundColor: 'var(--color-surface)', borderColor: 'var(--color-border)' }}
      >
        <h2 className="text-sm font-bold mb-3">How does it work?</h2>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          {[
            { step: '1', title: 'Choose a template', desc: 'Select the template that best fits your market (Crypto or Polymarket)' },
            { step: '2', title: 'Adjust parameters', desc: 'Modify RSI, momentum, stop loss values and more with simple controls' },
            { step: '3', title: 'Backtest & Live', desc: 'The strategy is saved automatically and becomes available for backtesting and live trading' },
          ].map(item => (
            <div key={item.step} className="flex gap-3">
              <div
                className="w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5"
                style={{ backgroundColor: 'var(--color-accent)', color: '#000' }}
              >
                {item.step}
              </div>
              <div>
                <p className="text-sm font-semibold mb-0.5">{item.title}</p>
                <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>{item.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* About Polymarket Binary windows */}
      <div
        className="rounded-lg border p-5 mb-8"
        style={{ backgroundColor: 'rgba(0,255,136,0.03)', borderColor: 'rgba(0,255,136,0.15)' }}
      >
        <div className="flex items-start gap-3">
          <BarChart2 size={16} className="mt-0.5 flex-shrink-0" style={{ color: 'var(--color-accent)' }} />
          <div>
            <h3 className="text-sm font-semibold mb-2" style={{ color: 'var(--color-accent)' }}>
              Polymarket Binary recurring series (BTC/ETH + Weather)
            </h3>
            <p className="text-xs mb-3" style={{ color: 'var(--color-text-muted)' }}>
              The engine supports a series registry with generic resolution: <code>price_up</code>, <code>threshold_above</code> and <code>threshold_below</code>.
              BTC/ETH uses Binance 1m candles and Weather uses Open-Meteo daily. In both cases, window resolution is automatic.
            </p>
            <pre
              className="text-xs p-3 rounded font-mono mb-2"
              style={{ backgroundColor: 'var(--color-surface)', color: 'var(--color-text)' }}
            >
{`# BTC 5m slug example (price_up)
window_ts = now - (now % 300)
slug = f"btc-updown-5m-{window_ts}"

# Weather uses threshold_* series (no CLOB slug)
# series_id: munich_temp_daily | london_temp_daily | nyc_temp_daily`}
            </pre>
            <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>
              Use <strong style={{ color: 'var(--color-accent)' }}>Polymarket BTC UP/DOWN</strong> for recurring crypto series,
              or <strong style={{ color: 'var(--color-accent)' }}>Polymarket Weather Binary</strong> for threshold markets.
              Then in Backtesting select <em>Market: Polymarket Binary</em>, pick <em>series_id</em> and run 3 months of data.
            </p>
          </div>
        </div>
      </div>

      {/* Agent Skills section (preserved) */}
      {skills.length > 0 && (
        <div>
          <div className="flex items-center gap-2 mb-4">
            <div className="w-1 h-5 rounded" style={{ backgroundColor: 'var(--color-border)' }} />
            <h2 className="text-sm font-bold uppercase tracking-widest" style={{ color: 'var(--color-text-muted)' }}>
              Installed Agent Skills
            </h2>
            <span
              className="text-xs px-2 py-0.5 rounded"
              style={{ backgroundColor: 'var(--color-surface-2)', color: 'var(--color-text-muted)' }}
            >
              {skills.length}
            </span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {skills.map(skill => (
              <div
                key={skill.name}
                className="rounded-lg border p-4"
                style={{ backgroundColor: 'var(--color-surface)', borderColor: 'var(--color-border)' }}
              >
                <div className="flex items-start justify-between mb-2">
                  <div className="flex items-center gap-2">
                    <Package size={13} style={{ color: 'var(--color-accent)' }} />
                    <span className="text-sm font-semibold">{skill.name}</span>
                  </div>
                  <button
                    onClick={() => setViewingSkill(skill)}
                    className="p-1 rounded hover:bg-white/5"
                    style={{ color: 'var(--color-text-muted)' }}
                  >
                    <Eye size={12} />
                  </button>
                </div>
                <p className="text-xs line-clamp-2 mb-2" style={{ color: 'var(--color-text-muted)' }}>
                  {skill.description}
                </p>
                <div className="flex gap-1 flex-wrap">
                  {skill.tags.slice(0, 3).map(tag => (
                    <span
                      key={tag}
                      className="text-[10px] px-1.5 py-0.5 rounded"
                      style={{ backgroundColor: 'var(--color-surface-2)', color: 'var(--color-text-muted)' }}
                    >
                      {tag}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Skills marketplace teaser */}
      <div
        className="rounded-lg border p-4 mt-6"
        style={{ backgroundColor: 'var(--color-surface)', borderColor: 'var(--color-border)' }}
      >
        <div className="flex items-center gap-3">
          <div className="p-2 rounded" style={{ backgroundColor: 'var(--color-accent-dim)' }}>
            <Store size={18} style={{ color: 'var(--color-accent)' }} />
          </div>
          <div className="flex-1">
            <h2 className="text-sm font-semibold">Skills Marketplace</h2>
            <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>
              Coming soon: download community strategies
            </p>
          </div>
          <button
            disabled
            className="flex items-center gap-2 px-3 py-1.5 rounded text-sm font-medium opacity-40 cursor-not-allowed"
            style={{ backgroundColor: 'var(--color-accent)', color: '#000' }}
          >
            <ExternalLink size={13} />
            Browse
          </button>
        </div>
      </div>

      {/* Wizard modal */}
      {selectedTemplate && (
        <StrategyWizard
          template={selectedTemplate}
          scriptsBasePath={scriptsBasePath}
          onClose={() => setSelectedTemplate(null)}
          onCreated={handleCreated}
        />
      )}

      {/* Skill viewer modal */}
      {viewingSkill && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60" onClick={() => setViewingSkill(null)}>
          <div
            className="rounded-lg border w-full max-w-lg max-h-[70vh] flex flex-col"
            style={{ backgroundColor: 'var(--color-surface)', borderColor: 'var(--color-border)' }}
            onClick={e => e.stopPropagation()}
          >
            <div className="flex items-center justify-between p-4 border-b" style={{ borderColor: 'var(--color-border)' }}>
              <div>
                <h2 className="font-semibold text-sm">{viewingSkill.name}</h2>
                <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>v{viewingSkill.version}</p>
              </div>
              <button onClick={() => setViewingSkill(null)} style={{ color: 'var(--color-text-muted)' }}>
                <X size={16} />
              </button>
            </div>
            <div className="p-4 overflow-auto flex-1">
              <p className="text-sm mb-3" style={{ color: 'var(--color-text)' }}>{viewingSkill.description}</p>
              <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>
                Location: <code className="px-1 rounded" style={{ backgroundColor: 'var(--color-surface-2)' }}>{viewingSkill.location}</code>
              </p>
            </div>
            <div className="p-4 border-t flex justify-end" style={{ borderColor: 'var(--color-border)' }}>
              <button
                onClick={() => setViewingSkill(null)}
                className="px-4 py-2 rounded text-sm font-medium"
                style={{ backgroundColor: 'var(--color-accent)', color: '#000' }}
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
